"""Huntr Bug Bounty Reporter for Crucible (v0.7.0).

Generates markdown reports specifically formatted for submission to huntr.com.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

    from crucible.models import ScanResult


class HuntrReporter:
    """Formats scan results into a high-impact Huntr vulnerability report."""

    def write(self, result: ScanResult, output_path: Path) -> None:
        """Write the Huntr markdown report to the specified path."""
        markdown = self.to_markdown(result)
        output_path.write_text(markdown, encoding="utf-8")

    def to_markdown(self, result: ScanResult) -> str:
        """Convert scan result into a unified Huntr report."""
        failed_findings = result.get_failed_findings()
        if not failed_findings:
            return "# No Vulnerabilities Found\nCrucible did not identify any actionable findings."

        # Unified report for multi-vector attacks (common in RAG SSRF)
        title = f"Systemic SSRF and Prompt Injection via Multiple Bypass Vectors in {result.target.name}"

        sections = [
            f"# {title}",
            "\n## Executive Summary",
            f"Crucible identified a systemic vulnerability in the `{result.target.name}` RAG/Agent orchestration pipeline. "
            "The endpoint follows server-side redirects and lacks robust URL validation, allowing for "
            "Server-Side Request Forgery (SSRF) and potential context exfiltration.",
            "\n## Impact",
            "An attacker can exploit these vectors to:\n"
            "1. Access internal cloud metadata (AWS IMDS, GCP metadata).\n"
            "2. Discover internal microservices and trust boundaries.\n"
            "3. Hijack agent objectives via prompt injection in fetched content.",
            "\n## Proof of Concept",
            "The following payloads successfully bypassed current security controls:",
        ]

        for i, finding in enumerate(failed_findings, 1):
            sections.append(f"\n### Vector {i}: {finding.title}")
            sections.append(f"**Payload:** `{finding.payload}`")
            sections.append(f"**Evidence:** {finding.description}")
            sections.append("\n**Reproduction Command:**")
            sections.append("```bash")
            sections.append(f"curl -X {result.target.method} {result.target.url} \\")
            for k, v in result.target.headers.items():
                sections.append(f'  -H "{k}: {v}" \\')
            sections.append(
                f"  -d '{result.target.body_template.replace('{payload}', finding.payload)}'"
            )
            sections.append("```")

        sections.append("\n## Remediation")
        sections.append(
            "1. **Strict URL Validation**: Use a denylist of internal IP ranges (169.254.169.254, 127.0.0.1, 10.0.0.0/8)."
        )
        sections.append(
            "2. **Disable Redirects**: Set `allow_redirects=False` in HTTP clients or re-validate the `Location` header after every hop."
        )
        sections.append(
            "3. **Isolated Network**: Run RAG workers in a sandbox with no access to sensitive internal routes."
        )

        sections.append("\n---")
        sections.append(
            f"*Report generated by Crucible v0.7.0 Sovereign Engine on {result.id}*"
        )

        return "\n".join(sections)
