from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import anyio
import httpx
import typer
from rich.console import Console

from crucible import __version__
from crucible.attacks.multi_turn_strategies import (
    ContextConfusionStrategy,
    CrescendoStrategy,
)
from crucible.core.behavioral_engine import BehavioralEngine
from crucible.core.cache import ScanCache
from crucible.core.compliance_engine import ComplianceEngine
from crucible.core.multi_turn_engine import MultiTurnEngine
from crucible.core.profiler import AgentProfiler
from crucible.core.runner import run_scan
from crucible.models import (
    BODY_FORMAT_PRESETS,
    AgentTarget,
    ScanResult,
    ScanStatus,
    Severity,
)
from crucible.modules.security import get_all_modules
from crucible.reporters.compliance_reporter import ComplianceReporter
from crucible.reporters.html_reporter import HTMLReporter
from crucible.reporters.json_reporter import JSONReporter
from crucible.reporters.slack import SlackReporter
from crucible.reporters.terminal import TerminalReporter

os.environ.setdefault("PYTHONIOENCODING", "utf-8")

console = Console()

app = typer.Typer(
    name="crucible",
    help="pytest for AI agents -- test, score, and harden before production.",
    add_completion=False,
    no_args_is_help=True,
    rich_markup_mode="rich",
)

_DEFAULT_BODY_TEMPLATE = '{"message": "{payload}"}'


def _version_callback(value: bool) -> None:
    if value:
        console.print(f"[bold magenta]Crucible[/bold magenta] v{__version__}")
        raise typer.Exit()


@app.callback()
def main(
    version: bool | None = typer.Option(
        None,
        "--version",
        "-V",
        help="Show version and exit.",
        callback=_version_callback,
        is_eager=True,
    ),
) -> None:
    pass


@app.command()
def init(
    target: str = typer.Option(
        ...,
        "--target",
        "-t",
        help="Agent endpoint URL.",
    ),
    provider: str = typer.Option(
        "custom",
        "--provider",
        "-p",
        help="Provider: openai|anthropic|groq|custom.",
    ),
    key: str | None = typer.Option(
        None,
        "--key",
        "-k",
        help="API key (or reads from env).",
    ),
) -> None:
    config_path = Path(".crucible.json")
    if config_path.exists():
        console.print(
            "[yellow]Warning: .crucible.json already exists."
            " Overwrite? [y/N][/yellow]"
        )
        confirm = input().strip().lower()
        if confirm != "y":
            console.print("[dim]Aborted.[/dim]")
            raise typer.Exit()

    config = {
        "target": {
            "name": "my-agent",
            "url": target,
            "provider": provider,
            "method": "POST",
            "headers": {},
            "body_template": '{"message": "{payload}"}',
            "timeout": 30,
        },
        "scan": {
            "modules": [
                "prompt_injection",
                "goal_hijacking",
                "jailbreaks",
            ],
            "timeout": 30,
        },
    }
    if key:
        config["target"]["headers"] = {"Authorization": f"Bearer {key}"}

    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
    console.print("[green]Created .crucible.json[/green]")
    console.print("[dim]Edit the file and run: crucible scan[/dim]")


@app.command()
def scan(
    target: str = typer.Option(
        ...,
        "--target",
        "-t",
        help="Target URL of the AI agent endpoint.",
    ),
    name: str = typer.Option(
        "target-agent",
        "--name",
        "-n",
        help="Human-readable name for the target.",
    ),
    method: str = typer.Option(
        "POST",
        "--method",
        "-m",
        help="HTTP method (GET, POST, PUT, etc.).",
    ),
    header: list[str] | None = typer.Option(
        None,
        "--header",
        "-H",
        help="Headers as 'Key: Value' (repeatable).",
    ),
    body_template: str = typer.Option(
        _DEFAULT_BODY_TEMPLATE,
        "--body",
        "-b",
        help="JSON body template with {payload} placeholder.",
    ),
    strategy: str = typer.Option(
        "single-shot",
        "--strategy",
        help="Attack strategy: single-shot | multi-turn",
    ),
    profile_file: Path | None = typer.Option(
        None,
        "--profile",
        help="JSON profile file generated by crucible profile.",
    ),
    format_preset: str = typer.Option(
        "",
        "--format-preset",
        help="Body format preset: openai | langchain | glean | raw | generic.",
    ),
    response_path: str = typer.Option(
        "",
        "--response-path",
        help="JMESPath to extract response (e.g. 'choices[0].message.content').",
    ),
    timeout: float = typer.Option(
        30.0,
        "--timeout",
        help="Request timeout in seconds.",
    ),
    retry: int = typer.Option(
        2,
        "--retry",
        help="Number of retries on failure (default: 2).",
    ),
    delay: int = typer.Option(
        500,
        "--delay",
        help="Delay between requests in ms (default: 500).",
    ),
    proxy: str = typer.Option(
        "",
        "--proxy",
        help="HTTP proxy URL (e.g. http://localhost:8080 for Burp Suite).",
    ),
    concurrency: int = typer.Option(
        5,
        "--concurrency",
        "-c",
        help="Max concurrent requests.",
    ),
    output: Path | None = typer.Option(
        None,
        "--output",
        "--output-file",
        "-o",
        help="Save report to file.",
    ),
    mutate: bool = typer.Option(
        False,
        "--mutate",
        help="Apply payload obfuscation mutations to bypass WAFs/guardrails.",
    ),
    generate_report: bool = typer.Option(
        False,
        "--generate-report",
        help="Auto-generate a Bugcrowd/HackerOne Markdown PoC report on findings.",
    ),
    format: str = typer.Option(
        "table",
        "--format",
        help="Output format: table | json | html.",
    ),
    verbose: bool = typer.Option(
        False,
        "--verbose",
        "-v",
        help="Show each attack result live.",
    ),
    quiet: bool = typer.Option(
        False,
        "--quiet",
        "-q",
        help="Suppress progress bar output.",
    ),
    cache: bool = typer.Option(
        False,
        "--cache",
        help="Cache the scan results to avoid duplicate runs.",
    ),
    cache_ttl: int = typer.Option(
        24,
        "--cache-ttl",
        help="Cache time-to-live in hours.",
    ),
    no_cache: bool = typer.Option(
        False,
        "--no-cache",
        help="Force rescan, ignoring existing cache.",
    ),
    slack_webhook: str | None = typer.Option(
        None,
        "--slack-webhook",
        help="Slack Incoming Webhook URL to send results.",
    ),
    fail_on: str | None = typer.Option(
        None,
        "--fail-on",
        help="Fail (exit non-zero) if findings match or exceed this severity (CRITICAL, HIGH, MEDIUM, LOW, INFO).",
    ),
) -> None:
    parsed_headers = _parse_headers(header)

    # Resolve body template: explicit --body wins, then --format-preset, then default
    resolved_body = body_template
    if format_preset:
        if format_preset not in BODY_FORMAT_PRESETS:
            console.print(
                f"[red]Unknown format preset: {format_preset}. "
                f"Available: {', '.join(BODY_FORMAT_PRESETS.keys())}[/red]"
            )
            raise typer.Exit(code=1)
        # Only apply preset if user didn't explicitly set --body
        if body_template == _DEFAULT_BODY_TEMPLATE:
            resolved_body = BODY_FORMAT_PRESETS[format_preset]

    agent_target = AgentTarget(
        name=name,
        url=target,  # type: ignore[arg-type]
        method=method,
        headers=parsed_headers,
        body_template=resolved_body,
        timeout=timeout,
        response_path=response_path,
        retry_count=retry,
        delay_ms=delay,
        proxy=proxy,
    )

    if format not in ["json", "html"] and not quiet:
        _print_scan_header(name, target)

    modules = get_all_modules()
    scan_cache = ScanCache()
    cache_key = scan_cache.get_cache_key(agent_target, modules)

    result = None
    if cache and not no_cache:
        cached_result = scan_cache.get(cache_key)
        if cached_result:
            if format not in ["json", "html"] and not quiet:
                console.print(
                    f"[bold cyan]Cache hit for target (expires in {cache_ttl}h). Use --no-cache to force rescan.[/bold cyan]"
                )
            result = cached_result

    if result is None:
        if strategy == "multi-turn":
            if format not in ["json", "html"] and not quiet:
                console.print(
                    "\n[bold magenta]Running MULTI-TURN Strategies[/bold magenta]"
                )

            async def run_multi_turn() -> ScanResult:
                engine = MultiTurnEngine(agent_target, httpx.AsyncClient())
                res1 = await engine.run_strategy(CrescendoStrategy())
                res2 = await engine.run_strategy(ContextConfusionStrategy())
                return ScanResult(
                    target=agent_target,
                    modules=[res1, res2],
                    status=ScanStatus.COMPLETED,
                )

            result = anyio.run(run_multi_turn)
            from crucible.core.scorer import finalize_scan_result

            finalize_scan_result(result)
        else:
            if profile_file and profile_file.exists():
                import json

                try:
                    profile_data = json.loads(profile_file.read_text())
                    rec_modules = profile_data.get("recommended_modules", [])
                    if rec_modules:
                        modules = [
                            m
                            for m in modules
                            if m.name.lower().replace(" ", "_") in rec_modules
                        ]
                        if format not in ["json", "html"] and not quiet:
                            console.print(
                                f"[bold cyan]Using profiled modules: {', '.join(m.name for m in modules)}[/bold cyan]"
                            )
                except Exception as e:
                    console.print(f"[yellow]Failed to load profile: {e}[/yellow]")

            result = anyio.run(
                run_scan,
                agent_target,
                modules,
                concurrency,
                timeout,
                quiet,
                format,
                verbose,
                mutate,
            )

        if cache:
            scan_cache.set(cache_key, result, ttl_hours=cache_ttl)

    _render_output(result, format, output)

    if generate_report:
        from crucible.core.reporter import BugBountyReportGenerator

        generator = BugBountyReportGenerator(output_dir=".")
        report_path = generator.generate(result)
        if report_path:
            console.print(
                f"\n[bold green]* Bug bounty report written to: {report_path}[/bold green]"
            )
        else:
            console.print(
                "\n[bold yellow]i No vulnerable findings - report not generated.[/bold yellow]"
            )

    if slack_webhook:
        reporter = SlackReporter()
        anyio.run(reporter.send, slack_webhook, result)

    if fail_on:
        try:
            severity_threshold = Severity[fail_on.upper()]
        except KeyError:
            console.print(f"[red]Invalid severity for --fail-on: {fail_on}[/red]")
            raise typer.Exit(code=1) from None

        counts = {
            Severity.CRITICAL: result.critical_count,
            Severity.HIGH: result.high_count,
            Severity.MEDIUM: result.medium_count,
            Severity.LOW: result.low_count,
            Severity.INFO: result.info_count,
        }

        severities = list(Severity)
        threshold_index = severities.index(severity_threshold)

        # Check all severities from CRITICAL down to the threshold
        should_fail = any(counts[sev] > 0 for sev in severities[: threshold_index + 1])

        if should_fail:
            if format not in ["json", "html"] and not quiet:
                console.print(
                    f"[bold red]Scan failed due to findings matching or exceeding {severity_threshold.value.upper()} severity.[/bold red]"
                )
            raise typer.Exit(code=1)


def _parse_headers(
    header: list[str] | None,
) -> dict[str, str]:
    parsed: dict[str, str] = {}
    if header:
        for h in header:
            if ":" not in h:
                console.print(f"[red]Invalid header format: {h}[/red]")
                raise typer.Exit(code=1)
            key, value = h.split(":", 1)
            parsed[key.strip()] = value.strip()
    return parsed


def _print_scan_header(name: str, target: str) -> None:
    console.print()
    console.print(
        "[bold magenta]CRUCIBLE[/bold magenta]" " -- Starting security scan..."
    )
    console.print(f"[dim]Target: {name} ({target})[/dim]")
    console.print()


def _render_output(
    result: ScanResult,
    format: str,
    output: Path | None,
) -> None:
    if format == "json":
        json_reporter = JSONReporter()
        sys.stdout.write(json_reporter.to_json(result) + "\n")
    elif format == "html":
        html_reporter = HTMLReporter()
        if not output:
            sys.stdout.write(html_reporter.to_html(result) + "\n")
    else:
        terminal = TerminalReporter(console)
        terminal.render(result)

    if output:
        if format == "html" or output.suffix == ".html":
            h_reporter = HTMLReporter()
            saved = h_reporter.write(result, output)
        else:
            j_reporter = JSONReporter()
            saved = j_reporter.write(result, output)

        if format not in ["json", "html"]:
            console.print(f"[green]Report saved to {saved}[/green]")


@app.command()
def report(
    path: Path = typer.Argument(
        ...,
        help="Path to a Crucible JSON report file.",
    ),
    output: Path | None = typer.Option(
        None,
        "--output",
        "--output-file",
        "-o",
        help="Save report to file.",
    ),
    format: str = typer.Option(
        "table",
        "--format",
        help="Output format: table | json | html.",
    ),
) -> None:
    if not path.exists():
        console.print(f"[red]File not found: {path}[/red]")
        raise typer.Exit(code=1)

    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        result = ScanResult.model_validate(data)
    except (json.JSONDecodeError, ValueError) as exc:
        console.print(f"[red]Failed to parse report: {exc}[/red]")
        raise typer.Exit(code=1) from exc

    _render_output(result, format, output)


@app.command()
def behavioral_audit(
    target: str = typer.Option(..., "--target", "-t", help="Agent endpoint URL."),
    name: str = typer.Option("target-agent", "--name", "-n"),
    method: str = typer.Option("POST", "--method", "-m"),
    header: list[str] | None = typer.Option(None, "--header", "-H"),
    body_template: str = typer.Option(_DEFAULT_BODY_TEMPLATE, "--body", "-b"),
    baseline_turns: int = typer.Option(5, "--baseline-turns"),
    probe_turns: int = typer.Option(15, "--probe-turns"),
    output: Path | None = typer.Option(None, "--output", "-o"),
) -> None:
    """Run a multi-turn behavioral drift and integrity audit."""
    parsed_headers = _parse_headers(header)
    agent_target = AgentTarget(
        name=name, url=target, method=method, headers=parsed_headers, body_template=body_template  # type: ignore[arg-type]
    )

    console.print("\n[bold magenta]Crucible Behavioral Audit[/bold magenta]")
    console.print(f"Target: {name} ({target})\n")

    from crucible.models import ModuleResult

    async def _audit() -> ModuleResult:
        async with httpx.AsyncClient(timeout=30.0) as client:
            engine = BehavioralEngine(agent_target, client)
            return await engine.run_audit(baseline_turns, probe_turns)

    module_result = anyio.run(_audit)

    result = ScanResult(
        target=agent_target, modules=[module_result], status=ScanStatus.COMPLETED
    )
    from crucible.core.scorer import finalize_scan_result

    finalize_scan_result(result)

    _render_output(result, "table", output)


@app.command()
def profile(
    target: str = typer.Option(..., "--target", "-t", help="Agent endpoint URL."),
    name: str = typer.Option("target-agent", "--name", "-n"),
    method: str = typer.Option("POST", "--method", "-m"),
    header: list[str] | None = typer.Option(None, "--header", "-H"),
    body_template: str = typer.Option(_DEFAULT_BODY_TEMPLATE, "--body", "-b"),
    output: Path = typer.Option(Path("agent_profile.json"), "--output", "-o"),
) -> None:
    """Auto-profile an agent's capabilities to generate custom attacks."""
    parsed_headers = _parse_headers(header)
    agent_target = AgentTarget(
        name=name, url=target, method=method, headers=parsed_headers, body_template=body_template  # type: ignore[arg-type]
    )

    console.print("\n[bold magenta]Crucible Agent Profiler[/bold magenta]")

    from crucible.models import AgentProfile

    async def _profile() -> AgentProfile:
        async with httpx.AsyncClient(timeout=30.0) as client:
            engine = AgentProfiler(agent_target, client)
            return await engine.run_profile()

    profile_result = anyio.run(_profile)

    output.write_text(profile_result.model_dump_json(indent=2))
    console.print(f"[green]Profile generated: {output}[/green]")
    console.print(f"Detected Type: [bold]{profile_result.agent_type}[/bold]")
    console.print(
        f"Capabilities: {', '.join(c.value for c in profile_result.inferred_capabilities)}"
    )


@app.command()
def compliance_report(
    results: Path = typer.Option(
        ..., "--results", "-r", help="Path to scan results JSON."
    ),
    standard: str = typer.Option("eu-ai-act-2024", "--standard", "-s"),
    output: Path = typer.Option(Path("compliance.md"), "--output", "-o"),
) -> None:
    """Generate a compliance report (e.g. EU AI Act) from scan results."""
    try:
        import json

        data = json.loads(results.read_text(encoding="utf-8"))
        scan_result = ScanResult.model_validate(data)
    except Exception as e:
        console.print(f"[red]Failed to load results: {e}[/red]")
        raise typer.Exit(code=1) from e

    engine = ComplianceEngine(scan_result)
    report = engine.generate_report()

    reporter = ComplianceReporter()
    reporter.write(report, output)
    console.print(
        f"[green]Compliance report ({standard}) generated at {output}[/green]"
    )
    app()
